fix: support changing of log level within the tool
Capgemini/xrm-datamigration-xrmtoolbox pull request #44
Opened 2021-12-23 22:37 UTC by realekhor

2022-01-01 18:41 UTC, tdashworth commented
@realekhor thanks for this. Happy to review this in a few days.

2022-01-04 09:01 UTC, realekhor commented
thanks @tdashworth

2022-01-04 13:07 UTC, tdashworth commented
@realekhor Could the selection box be moved the to final page? 

![image](https://user-images.githubusercontent.com/9384593/148063643-907193d2-f6b7-46c3-bfac-fc7c483b7d61.png)

2022-01-04 13:09 UTC, realekhor commented
@tdashworth good point. I will try make the change.

2022-01-04 14:17 UTC, realekhor commented
@tdashworth controls now moved to requested pages. hope this is ok.

2022-01-04 14:24 UTC, realekhor commented
@tdashworth looks like i need to add more code coverage tests :(

2022-01-05 09:29 UTC, realekhor commented
@tdashworth not sure we ever went beyond 75% coverage :). so i think it is ready

2022-01-05 10:07 UTC, tdashworth commented
> @tdashworth not sure we ever went beyond 75% coverage :). so i think it is ready

Agreed, our code coverage isn't as high as we'd like. Please could we add tests for these two lines:

- https://sonarcloud.io/code?id=xrm-datamigration-xrmtoolbox&pullRequest=44&selected=xrm-datamigration-xrmtoolbox%3ACapgemini.Xrm.CdsDataMigrator%2FCapgemini.Xrm.CdsDataMigratorLibrary%2FUserControls%2FImportWizard.cs&line=224
- https://sonarcloud.io/code?id=xrm-datamigration-xrmtoolbox&pullRequest=44&selected=xrm-datamigration-xrmtoolbox%3ACapgemini.Xrm.CdsDataMigrator%2FCapgemini.Xrm.CdsDataMigratorLibrary%2FUserControls%2FExportWizard.cs&line=192

2022-01-12 13:43 UTC, tdashworth submitted a review, later dismissed

2022-01-21 15:05 UTC, tdashworth requested changes

2022-01-21 15:05 UTC, tdashworth commented on Capgemini.Xrm.CdsDataMigrator/Capgemini.Xrm.CdsDataMigratorLibrary.Tests.Unit/Presenters/ExportPresenterTests.cs
> +            FluentActions.Invoking(() => systemUnderTest./*ExportDataAction*/ExportData(null, new EventArgs()))
Can this comment be removed? 
```suggestion
            FluentActions.Invoking(() => systemUnderTest.ExportData(null, new EventArgs()))
```

2022-01-21 15:05 UTC, tdashworth commented on Capgemini.Xrm.CdsDataMigrator/Capgemini.Xrm.CdsDataMigratorLibrary.Tests.Unit/Presenters/ExportPresenterTests.cs
> +            FluentActions.Invoking(() => systemUnderTest./*ExportDataAction*/ExportData(null, new EventArgs()))
Can this comment be removed? 
```suggestion
            FluentActions.Invoking(() => systemUnderTest.ExportData(null, new EventArgs()))
```

2022-01-21 15:36 UTC, realekhor commented on Capgemini.Xrm.CdsDataMigrator/Capgemini.Xrm.CdsDataMigratorLibrary.Tests.Unit/Presenters/ExportPresenterTests.cs
> +            FluentActions.Invoking(() => systemUnderTest./*ExportDataAction*/ExportData(null, new EventArgs()))
addressed in latest commit

2022-01-21 15:40 UTC, tdashworth approved these changes

2022-01-21 15:40 UTC, tdashworth commented
@realekhor Thank you so much for the work you've put into this. It's very much appreciated!

2022-01-21 16:24 UTC, merged