Refactor/import page
Capgemini/xrm-datamigration-xrmtoolbox pull request #66
Opened 2022-07-22 14:10 UTC by danroche10

2022-07-24 08:29 UTC, tdashworth commented
Looking really good so far Dan, thanks for all the effort! A few comments for you and one general testing one. 

Could the test names be consistent? I noticed some have `_` before the `When` and others don't. Either is fine, I'm just being OCD 😋

2022-07-24 08:30 UTC, tdashworth requested changes

2022-07-24 08:30 UTC, tdashworth commented on Capgemini.Xrm.CdsDataMigrator/Capgemini.Xrm.CdsDataMigratorLibrary.Tests.Unit/Presenters/ImportPagePresenterTests.cs
> +            mockImportView.VerifyAll();
Could we verify here that the file does not exist?

2022-07-25 11:14 UTC, danroche10 commented
> Looking really good so far Dan, thanks for all the effort! A few comments for you and one general testing one.
> 
> Could the test names be consistent? I noticed some have `_` before the `When` and others don't. Either is fine, I'm just being OCD 😋

Thanks Tom! I've implemented requested changes

2022-07-26 07:59 UTC, tdashworth approved these changes

2022-07-26 08:42 UTC, merged